sudo: required

services:
  - docker

before_install:
  - docker build -t luvwadhwani/fibonaci-test -f ./client/Dockerfile-dev ./client

script:
  - docker run -e CI=true luvwadhwani/fibonaci-test npm run test

after_success:
  - docker build -t luvwadhwani/multi-client ./client
  - docker build -t luvwadhwani/multi-nginx ./nginx
  - docker build -t luvwadhwani/multi-server ./server
  - docker build -t luvwadhwani/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push luvwadhwani/multi-client
  - docker push luvwadhwani/multi-nginx
  - docker push luvwadhwani/multi-server
  - docker push luvwadhwani/multi-worker