version: '3.4'

services:
  nginx:
    image: "luvwadhwani/multi-nginx"
    restart: always
    hostname: nginx
    ports:
      - "80:80"
  api:
    image: "luvwadhwani/multi-server"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
  client:
    image: "luvwadhwani/multi-client"
    hostname: client
  worker:
    image: "luvwadhwani/multi-worker"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    hostname: worker